name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    strategy:
      matrix:
        os:
          - ubuntu-18.04
        node-version:
          - 12.x
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run check
      - run: npm run lint
